### ISSUE TITLE
Why not *.sh files?

### ISSUE THREAD

**Issue by Rudxain** [jbara2002/melody_android#1]
Why is every command in the `README`?

I understand that it's "better" if we want to select individual commands, but what if we want to select all commands?

I propose moving groups of commands to individual script files, each with its own category name, and have a `main.sh` that executes all scripts. This way, users can easily choose individual cmds, groups, or all simultaneously.

I'm willing to open a PR, but I don't have time nowadays

**Comment by ionuttbara** [comment]
because *.sh files are used in linux... and i can't run script on my Android Phone

**Comment by Rudxain** [comment]
> can't run script on my Android

True, but ADB can be executed on Termux:
```sh
pkg install android-tools
```

Of course, the setup is awkward on newer Android versions, because of the security restrictions. On older versions, the only way is to use a 2nd device that tells the 1st device to listen on a specific TCP/IP port (I forgot the cmd), which has minimal security restrictions, but is still inconvenient

**Comment by ionuttbara** [comment]
its better for me to connect my android device with cable and run adb command, than termux and another things.

**Comment by Rudxain** [comment]
Ok, I understand that it's a matter of personal preference, I agree with that 👍
